### ISSUE TITLE
Sengled E11-N1EA Color Gamut Issues (xy-color conversion)

### ISSUE THREAD

**Issue by rem2157** [Koenkk/zigbee-shepherd-converters#303]
Using zigbee2mqtt 1.1.1 in Hassio, Element Plus Color (A19) (E11-N1EA) bulbs (RGB) have a distorted/reduced color range as compared to the native Sengled hub/app, particularly towards red. I believe this is due to the xy-color values being computed by zigbee-shepherd-converters.

I've sniffed the packets sent by the Sengled hub for pure red, green, and blue (as best can be picked in the Sengled app.)

`color: [red, green, blue]`
`zigbee2mqtt conversion: [{"x":0.701,"y":0.299}, {"x":0.172,"y":0.747}, {"x":0.136,"y":0.04}]`
`Sengled sniffed packets: [{"x":0.733,"y":0.264}, {"x":0.116,"y":0.818}, {"x":0.157,"y":0.019}]`

Calling a light service in hassio with "xy_color" values outside of [x:0.136,0.701] and [y:0.04,0.747] results in MQTT published values scaled to within those bounds. 

If someone could point me in the direction of the files to adjust for my Sengled only setup, and the logic to apply, I would appreciate it. [(here perhaps?)](https://github.com/Koenkk/zigbee-shepherd-converters/blob/983c9ef2cada1714ab49e146275d6bfab34aee8f/converters/utils.js#L17) 

Otherwise, a way to manually set the xy color triangle limits for non-hue bulbs through zigbee2mqtt would be fantastic.
 
Please let me know if this better posted elsewhere.

**Comment by Koenkk** [comment]
So xy is working probably, if that is indeed the case, the implementation of `rgbToXY` (the one you linked) needs to be fixed

**Comment by rm12656** [comment]
xy works correctly when calling the hassio service using `xy_color` values within the range of `[x : 0.136, 0.701]` and `[y : 0.04, 0.747]`. 

Outside of those ranges, the values are scaled to fall within them. Since the Sengled bulbs need `xy_color = [0.733, 0.264]`, this results in zigbee2mqtt being unable to assign a true red color to the bulb since `0.733 > 0.701`. 

For example, the color picker in hassio shows red, zigbee2mqtt shows `{"x":0.701,"y":0.299}` on the light's topic, but the bulb itself displays an orange-red color. I assume that `{"x":0.701,"y":0.299}` produces an actual pure red color on Hue bulbs (or close to it, according to the [developer docs here](https://developers.meethue.com/develop/application-design-guidance/color-conversion-formulas-rgb-to-xy-and-back/), requires registration), but these Sengled bulbs have a different range.

When the xy values are in the middle of color triangle, e.g. yellows and purples, the actual color shown on the bulb is generally acceptable compared to hassio's color pickers.

Thanks for your help on this, and your work on this great project.

**Comment by rem2157** [comment]
xy works correctly when calling the hassio service using xy_color values within the range of [x : 0.136, 0.701] and [y : 0.04, 0.747].

Outside of those ranges, the values are scaled to fall within them. Since the Sengled bulbs need xy_color = [0.733, 0.264], this results in zigbee2mqtt being unable to assign a true red color to the bulb since 0.733 > 0.701.

For example, the color picker in hassio shows red, zigbee2mqtt shows {"x":0.701,"y":0.299} on the light's topic, but the bulb itself displays an orange-red color. I assume that {"x":0.701,"y":0.299} produces an actual pure red color on Hue bulbs (or close to it, according to the developer docs here, requires registration), but these Sengled bulbs have a different range.

When the xy values are in the middle of color triangle, e.g. yellows and purples, the actual color shown on the bulb is generally acceptable compared to hassio's color pickers.

Thanks for your help on this, and your work on this great project.

**Comment by Koenkk** [comment]
So this is actually something from home assistant? Sending xy values that the bulb doesn't support? AFAIK there is no configuration to limit the XY (https://www.home-assistant.io/components/light.mqtt/).

So I guess the best thing to do is to send RGB commands and use a different `rgbToXY` function. Let me know if you are able to find one, then we can integrate this in zigbee2mqtt.

**Comment by rem2157** [comment]
Yes, this limiting of XY values appears to be on Home Assistant's MQTT [Light](https://www.home-assistant.io/components/light.mqtt/) platform side of things, perhaps [here](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/util/color.py).

As you suggested and I tested, there is no limiting of the xy values when publishing a MQTT message directly to the light's topic. 

Thanks for your help. I'll do more reading to see if this (color gamut issues) is a config that can be handled in Home Assistant.

**Comment by ajlunis** [comment]
Still seeing this issue, is there any solution? Thanks!
